const applicationSettings = {
	app_domain: "www.freeriderhd.com",
	load_root_url: "",
	root_url: "https://www.freeriderhd.com",
	base_platform_url: "https://www.freeriderhd.com",
	base_platform_short_url: "http://frhd.co",
	base_platform_external_url: "https://www.freeriderhd.com",
	base_cdn_url: "https://cdn.freeriderhd.com/free_rider_hd",
	base_request_url: "https://www.freeriderhd.com",
	app_signed_request:
		"lCPSSrFK2RJvjYC8dyhFatNra1hzGWWdR8JwcoavGzo.eyJlbWFpbF90b2tlbiI6IjVlNmEwMGZjOWNiMmIiLCJ1X2lkIjo2MDIyNjQ1LCJwbGF0Zm9ybSI6IndlYiIsImRldmljZSI6ImRlc2t0b3AiLCJhbGdvcml0aG0iOiJITUFDLVNIQTI1NiIsImlzc3VlZF90cyI6MTYwNTQ1NDg0Nn0",
	platform: "web",
	device: "desktop",
	is_mobile: "",
	is_xbox: "",
	fb_app_id: "222244124602754",
	is_fb_canvas: false,
	is_fb_mobile: false,
	fb_graph_v: "v2.12",
	is_web: true,
	fb_signed_request: "",
	gg_analytics_enabled: "1",
	gg_analytics_code: "UA-45513212-1",
	gg_analytics_loaded: "1",
	dfp_ads_enabled: true,
	ios_app_url:
		"https://itunes.apple.com/app/apple-store/id773716739?pt=1198585&ct=web_side_banner&mt=8",
	android_app_url:
		"https://play.google.com/store/apps/details?id=com.kanoapps.frhd",
	rewarded_ads: {},
	features: {
		friends_enabled: 1,
		liked_tracks_enabled: 1,
	},
	user: {
		u_id: 6022645,
		u_name: "hornta",
		d_name: "hornta",
		verified: 1,
		mbl_cnctd: 0,
		sex: "unknown",
		locale: "",
		i_ts: 1584005372,
		l_ts: 1584005372,
		a_ts: 1605563104,
		f_ts: 0,
		img_url_small:
			"https://secure.gravatar.com/avatar/6044c8092e0e0e5a546244749a709aaa/?s=50&d=mm&r=pg",
		img_url_medium:
			"https://secure.gravatar.com/avatar/6044c8092e0e0e5a546244749a709aaa/?s=100&d=mm&r=pg",
		fb_id: 0,
		fbcnvs_id: 0,
		gg_id: "",
		kg_id: 0,
		frm_id: 23705,
		current_user: true,
		classic: false,
		admin: false,
		moderator: false,
		plus: false,
		install_day: "2020-03-12",
		install_week: "2020-11",
		install_month: "2020-03",
		t1_t2: "gg-desk",
		day: 249,
		campaign: {
			max_campaign_rewards: { pts: 3610, cns: 4150 },
			user_campaign_rewards: { pts: 2010, cns: 1650 },
			user_campaigns_rewards_percent: { pts: 56, cns: 40 },
			is_complete: false,
			current_id: 11,
			current_title: "Super Free Rider Bros",
			current_percent: 0,
		},
		friend_cnt: 1,
		platforms: "web",
	},
	user_stats: {
		u_id: 6022645,
		tot_pts: 3558,
		tot_cns: 1035,
		cmpltd: 774,
		rtd: 17,
		cmmnts: 0,
		beginner_pts: false,
		head_cnt: 42,
		total_head_cnt: 200,
	},
	t_1: "ref",
	t_2: "desk",
	app_version: "a6fd2f4244",
	cors_enabled: true,
	kg_embedded: false,
	status: 200,
	is_admin: false,
	is_moderator: false,
	share_metadata: {
		name: "Free Rider HD",
		caption: "Race a bike on tracks created by other players!",
		url: "https://www.freeriderhd.com?frhd_friend_add=hornta",
		action: "Play now",
		title: "Free Rider HD",
		subject: "free rider hd",
		body:
			"hey, checkout free rider hd it is an awesome new game, we can race each other ",
		description:
			"Free Rider HD is an addicting game where you race on tracks drawn by other players. Thousands of top tracks to play, challenge friends, draw the track of your dreams and more!",
		tweet: "Play Free Rider HD!",
		tweet_hashtags: "game",
		via: "freerider_hd",
	},
};

export default applicationSettings;
