const GameSettings = {
	// BaseAssetUrl: true,
	basePlatformExternalUrl: "https://www.freeriderhd.com",
	basePlatformUrl: "https://www.freeriderhd.com",
	defaultContainerID: "canvas",
	developerMode: false,
	drawFPS: 30,
	drawSectorSize: 300,
	embedded: false,
	fullscreen: false,
	fullscreenAvailable: true,
	height: 500,
	isChromeApp: false,
	isStandalone: false,
	physicsSectorSize: 100,
	platform: "web",
	portal: false,
	width: 900,
	startVehicle: "MTB",
	startTool: "straightline",
	startPowerup: "goal",
	defaultGravityX: 0,
	defaultGravityY: 0.3,
	cameraStartZoom: 0.5,
	cameraZoomMin: 0.1,
	cameraZoomMax: 4,
	cameraSensitivity: 0.2,
	lowQualityMode: false,
	device: "desktop",
	mobile: false,
	controls: false,
	startPaused: false,
	waitForKeyPress: true,
	waitAtCheckpoints: true,
	trackCodeVersion: 1,
	replayVersion: 1,
	physicsLineColor: "#000",
	sceneryLineColor: "#AAA",
	raceColors: [
		"rgba(57,185,117,1)",
		"rgba(0,152,189,1)",
		"rgba(151,95,162,1)",
		"rgba(253,85,91,1)",
		"rgba(245,126,64,1)",
		"rgba(247,212,62,1)",
		"rgba(170,221,114,1)",
		"rgba(72,217,207,1)",
		"rgba(0,124,212,1)",
		"rgba(226,108,216,1)",
	],
	toolHandler: {
		snap: false,
		snapLocked: false,
		cameraLocked: false,
		grid: false,
		gridSize: 10,
		visibleGrid: true,
		gridMinorLineColor: "#EEE",
		gridMajorLineColor: "#CCC",
		lineType: "physics",
		cameraMoveSpeed: 0.02,
		rightClickMove: false,
	},
	vehiclePowerup: {
		selected: "helicopter",
		time: 10,
		step: 1,
		minTime: 5,
		maxTime: 60,
	},
	eraser: {
		radius: 29,
		maxRadius: 200,
		minRadius: 2,
		radiusSizeSensitivity: 5,
		types: {
			scenery: true,
			physics: true,
			powerups: true,
		},
	},
	brush: {
		breakLength: 0.2,
		maxBreakLength: 3,
		minBreakLength: 0.02,
		breakLengthSensitivity: 0.1,
		trailSpeed: 1,
		maxTrailSpeed: 1,
		minTrailSpeed: 0.01,
		trailSpeedSensitivity: 0.005,
	},
	playHotkeys: {
		up: [38, 87],
		down: [40, 83],
		left: [37, 65],
		right: [39, 68],
		pause: 32,
		enter: 13,
		backspace: 8,
		restart: 82,
		z: 90,
		change_camera: 9,
		zoom_increase: 187,
		zoom_decrease: 189,
		zoom_100: 48,
		fullscreen: 70,
		change_vehicle: 86,
		exit_fullscreen: 27,
		settings: 220,
	},
	editorHotkeys: {
		up: 38,
		down: 40,
		left: 37,
		right: 39,
		z: 90,
		y: 89,
		snap: 17,
		lineType: 83,
		eraser: 69,
		straightline: 81,
		brush: 65,
		curve: 87,
		grid: 71,
		camera: 67,
		pause: 32,
		change_vehicle: 86,
		powerup: 80,
		vehiclepowerup: 79,
		opt1: 49,
		opt2: 50,
		opt3: 51,
		opt4: 52,
		opt5: 53,
		opt6: 54,
		opt7: 55,
		opt8: 56,
		enter: 13,
		restart: 82,
		backspace: 8,
		shift: 16,
		ctrl: 17,
		alt: 18,
		zoom_increase: 187,
		zoom_decrease: 189,
		zoom_100: 48,
		fullscreen: 70,
	},
	keysToRecord: ["up", "down", "left", "right", "enter", "backspace", "z"],
	user: {
		u_id: 6022645,
		u_name: "hornta",
		d_name: "hornta",
		img_url_small:
			"https://secure.gravatar.com/avatar/6044c8092e0e0e5a546244749a709aaa/?s=50&d=mm&r=pg",
		classic: false,
		plus: false,
		cosmetics: {
			head: {
				id: "1",
				title: "Classic Hat",
				type: "1",
				name: "classic",
				cost: "0",
				options: {
					back: "white",
				},
				classname: "forward_cap",
				equiped: true,
				spritesheet_id: "3",
				img: "head_icons_4 head_icons_4-classic",
				show: true,
				script:
					"https://cdn.freeriderhd.com/free_rider_hd/assets/inventory/head/scripts/v5/forward_cap.js",
				limited: false,
			},
		},
	},
	showHelpControls: false,
	isCampaign: false,
	track: {
		id: 50387,
		title: "Smooth Ride (old)",
		descr: "Old track, just uploaded for fun. :)",
		url: "50387-smooth-ride-old",
		vehicle: "MTB",
		vehicles: ["MTB", "BMX"],
		size: 65696,
		cdn:
			"https://cdn.freeriderhd.com/free_rider_hd/tracks/prd/a/99/50387/track-data-v1.js",
		pwrups: {
			gls: 1,
			chkpts: 0,
			bsts: 46,
			grvty: 0,
			slwmtn: 0,
			bmbs: 1,
		},
		u_id: 50041,
		author_is_user: true,
		u_url: "wheeliemaker",
		author: "WheelieMaker",
		img:
			"https://cdn.freeriderhd.com/free_rider_hd/tracks/prd/a/99/50387/250x150-v5.png",
		ft_ts: 0,
		featured: false,
		p_ts: 1400055094,
		hide: 0,
		admin: false,
	},
	userTrackStats: {
		best_time: false,
		runs: 0,
		plays: 7,
		up_vote: 0,
		dwn_vote: 0,
		vote: 0,
	},
	campaignData: false,
	trackUploadCost: 25,
	raceUids: [],
	raceData: false,
	soundsEnabled: false,
	bestGhostEnabled: true,
	requireTrackVerification: true,
};

export default GameSettings;
